---
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - './data:/etc/mosquitto'
      - './config:/mosquitto/config'
      - './log:/mosquitto/log'
